[phases.setup]
nixPkgs = ["jdk21"]

[phases.build]
cmds = ["chmod +x gradlew", "./gradlew clean build -x check -x test"]

[phases.start]
cmds = ["java -jar build/libs/projeto-api-java-nuvem-0.0.1-SNAPSHOT.jar"]
